/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectooriginal;

import controladores.InventarioJpaController;
import controladores.exceptions.NonexistentEntityException;
import entidades.Inventario;
import entidades.Vendedores;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alana
 */
public class CapturaVendedores extends javax.swing.JFrame {

    /**
     * Creates new form CapturaVendedores
     */
    public CapturaVendedores() {
        initComponents();
    }
  private void AgregarTabla(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Id");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellido Paterno");
        dtm.addColumn("Apellido Materno");
        dtm.addColumn("Correo");
        dtm.addColumn("Num Tel");
        
        Object[] fila = new Object[6];
        controladores.VendedoresJpaController cp = new controladores.VendedoresJpaController();
        List<Vendedores> lista = cp.findVendedoresEntities();
        for(Vendedores p:lista){
            fila[0] = p.getId();
            fila[1] = p.getNombre();
            fila[2] = p.getAp();
            fila[3] = p.getAm();
            fila[4] = p.getCorreo();
            fila[5] = p.getNum();
            dtm.addRow(fila);
        }
        tblInventario.setModel(dtm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAP = new javax.swing.JTextField();
        txtAM = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel1.setText("Registro Vendedores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(141, 6, 277, 35);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 100, 80, 16);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Apellido Paterno");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 160, 16);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Apellido Materno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 180, 170, 16);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 220, 80, 16);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Numero de telefono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 260, 183, 16);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 303, 0, 0);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(240, 90, 125, 24);
        getContentPane().add(txtAP);
        txtAP.setBounds(240, 130, 125, 24);
        getContentPane().add(txtAM);
        txtAM.setBounds(240, 170, 125, 24);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(240, 210, 125, 24);
        getContentPane().add(txtNum);
        txtNum.setBounds(240, 260, 125, 24);

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Correo", "Num Tel"
            }
        ));
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 360, 453, 110);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(60, 310, 83, 32);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(220, 310, 83, 32);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(400, 310, 76, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Vendedores inv = new Vendedores();
        inv.setNombre(txtNombre.getText());
        inv.setAp(txtAP.getText());
        inv.setAm(txtAM.getText());
        inv.setCorreo(txtCorreo.getText());
        inv.setNum(Integer.parseInt(txtNum.getText()));
        controladores.VendedoresJpaController ic = new controladores.VendedoresJpaController();
        ic.create(inv);
        JOptionPane.showMessageDialog(this, "Producto agregado");
        AgregarTabla();
        Limpiar();

    }//GEN-LAST:event_btnRegistrarActionPerformed

      private void Limpiar(){
        txtNombre.setText(" ");
        txtAP.setText("");
        txtAM.setText("");
        txtCorreo.setText("");
        txtNum.setText("");
    }
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int renglon = tblInventario.getSelectedRow();
        int id = (int)tblInventario.getValueAt(renglon, 0);
        Vendedores inv = new Vendedores();
        inv.setId(id);
        inv.setNombre(txtNombre.getText());
        inv.setAp(txtAP.getText());
        inv.setAm(txtAM.getText());
        inv.setCorreo(txtCorreo.getText());
        inv.setNum(Integer.parseInt(txtNum.getText()));
        controladores.VendedoresJpaController ic = new controladores.VendedoresJpaController();
        try {
            ic.edit(inv);
            AgregarTabla();
            Limpiar();
        } catch (Exception ex) {
            Logger.getLogger(CapturaInventario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int renglon = tblInventario.getSelectedRow();
        int id = (int)tblInventario.getValueAt(renglon, 0);
        controladores.VendedoresJpaController elim = new controladores.VendedoresJpaController();
        try {
            elim.destroy(id);
            Limpiar();
            AgregarTabla();
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(CapturaInventario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        
        
        
    }//GEN-LAST:event_formMouseClicked

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
       int renglon = tblInventario.getSelectedRow();
        txtNombre.setText(tblInventario.getValueAt(renglon, 1).toString());
        txtAP.setText(tblInventario.getValueAt(renglon, 2).toString());
        txtAM.setText(tblInventario.getValueAt(renglon, 3).toString());
        txtCorreo.setText(tblInventario.getValueAt(renglon, 4).toString());
        txtNum.setText(tblInventario.getValueAt(renglon, 5).toString());
        
        
        
        
        
    }//GEN-LAST:event_tblInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturaVendedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
